---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-logger
  labels:
    app: transaction-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-logger
  template:
    metadata:
      labels:
        app: transaction-logger
    spec:
      volumes:
      - name: source
        hostPath:
          path: /Users/pietrobongiovanni/workspace/apps/transaction-logger
      containers:
      - name: transaction-logger-node
        image: pgoodjohn/node:12.9
        workingDir: /source
        command: ["npm", "run", "start"]
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: source
            mountPath: /source
