---
apiVersion: v1
kind: Service
metadata:
  name: transaction-logger
spec:
  type: ClusterIP
  selector:
    app: transaction-logger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
